version: "3.8"

services:

  db:
    image: cockroachdb/cockroach:v22.2.7
    container_name: "db"
    environment:
      COCKROACH_DATABASE: ${COCKROACH_DATABASE}
      COCKROACH_USER: ${COCKROACH_USER}
      COCKROACH_PASSWORD: ${COCKROACH_PASSWORD}
    volumes:
      - /home/user/docker-volumes/bio-beacon-db-store:/cockroach/cockroach-data
      - /home/user/docker-volumes:/docker-entrypoint.initdb.d
    working_dir: /cockroach
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure

  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
        - "1883:1883" #default mqtt port
        - "9001:9001" #default mqtt port for websockets
    volumes:
        - /home/user/docker-volumes/mosquitto/config:/mosquitto/config:rw
        - /home/user/docker-volumes/mosquitto/data:/mosquitto/data:rw
        - /home/user/docker-volumes/mosquitto/log:/mosquitto/log:rw

  api:
    image: ghcr.io/nimshub/bio-beacon-api:latest
    container_name: "bio-beacon-api"
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    environment:
      PORT: ${API_PORT}
      SECRET_KEY: ${SECRET_KEY}
      PRIME_DB_URL: ${PRIME_DB_URL}
      PRIME_DB_USER: ${PRIME_DB_USER}
      PRIME_DB_PASSWORD: ${PRIME_DB_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

  nginx:
    image: ghcr.io/nimshub/nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - api

networks:
  default:
    name: mqtt5-network