server:
  port: ${PORT}

secret.key: ${SECRET_KEY}

spring:

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    password: ${MAIL_PASSWORD}
    username: ${MAIL_USERNAME}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: ${PRIME_DB_URL}
    username: ${PRIME_DB_USER}
    password: ${PRIME_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: public
    url: ${PRIME_DB_URL}
    user: ${PRIME_DB_USER}
    password: ${PRIME_DB_PASSWORD}
    enabled: true

scheduling:
  enabled: false
  fixed-rate: 10000

ml:
  enabled: ${ML_ENABLED}
  scripts: ${SCRIPTS_LOCATION}
  data: ${DATA_LOCATION}
  process-directory: ${PROCESS_DIRECTORY}

logging.level:
  org.hibernate: error
  com.nimshub: trace